### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by Mentheus** [MrTubzy456/Requiem-Experimental-V.-1#1]
since the patch 1.3 today it's no longer possible to hit any mobs.
tryed with weapons (sword & bow), Tools (axe & shovel), Blocks and also empty hands.

it's possible to break blocks and stuff (gras, torches, ...) but no longer can kill monsters and/or animals.

already tried to switch difficulties.

**Comment by Mentheus** [comment]
thanks for the fast update.

for me new version 1.32 just crashes.
Crash Report: http://pastebin.com/LDDf2fzf
Hope providing the crash report helps

**Comment by Mentheus** [comment]
patch 1.33 fixed problems and is running again
thanks for the fast patches, keep up the good work

**Comment by MrTubzy456** [comment]
Thanks for the report. Yeah, we like to keep things updated for you guys so that there is as little bugs as possible.
